# Generated by Django 5.1.3 on 2024-12-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('processing_start', models.DateTimeField(blank=True, null=True)),
                ('processing_end', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('original_language', models.CharField(blank=True, max_length=50, null=True)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='files.directory')),
                ('files', models.ManyToManyField(blank=True, related_name='directories', to='files.file')),
            ],
        ),
    ]
